export const cardDataArray = 
  [
    {
      text:"Problem Solving",
      image:"",
      rotate:"70deg",
      top:"30%",
      bottom:"",
      left:"5%",
    },
    {
      text:"Design Patterns",
      image:"",
      rotate:"-30deg",
      top:"70%",
      bottom:"",
      left:"30%",
    },
    {
      text:"KISS",
      image:"",
      rotate:"90deg",
      top:"",
      bottom:"30%",
      left:"75%"
    },
    {
      text:"SAP",
      image:"",
      rotate:"-45deg",
      top:"20%",
      bottom:"",
      left:"60%",
    },
    {
      text:"State Management",
      image:"",
      rotate:"20deg",
      top:"10%",
      bottom:"",
      left:"30%",

    },
    {
      text:"",
      image:"assets/logos/node-js-svgrepo-com.svg",
      rotate:"70deg",
      top:"70%",
      bottom:"70%",
      left:"25%",
    },
    {
      text:"",
      image:"assets/logos/typescript-svgrepo-com.svg",
      rotate:"30deg",
      top:"70%",
      bottom:"",
      left:"70%",
    },
    {
      text:"",
      image:"assets/logos/cplusplus.svg",
      rotate:"-25deg",
      top:"30%",
      bottom:"",
      left:"50%",
    },
  ]